apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-image-id
  annotations:
    policies.kyverno.io/category: OCI Best Practices
spec:
  rules:
    - name: check-image-id
      match:
        all:
          #- ($analyzer.resource.type): terraform-plan
          - (planned_values.root_module.child_modules[].resources[?type=='oci_core_instance'][] | length(@) > `0`): true
      assert:
        all:
          - message: Check that the right image is used and the image id is correct.
            check:
              ~.(planned_values.root_module.child_modules[].resources[?type=='oci_core_instance'][]):
                values:
                  ~.(source_details):
                    source_id: tiaa-approved*
