apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-instance-freeform-tags
  annotations:
    policies.kyverno.io/category: OCI Best Practices
    policies.kyverno.io/severity: Critical
spec:
  rules:
    - name: check-instance-freeform-tags
      match:
        all:
          # - ($analyzer.resource.type): terraform-plan
          - (planned_values.root_module.child_modules[].resources[?type=='oci_core_instance'][] | length(@) > `0`): true
      assert:
        any:
          - message: Check that Environment, AppID, and Name tags are defined for instances.
            check:
              ~.(planned_values.root_module.child_modules[].resources[?type=='oci_core_instance'][]):
                values:
                  freeform_tags:
                    Environment:
                      (length(@) > `0`): true
                    AppID:
                      (length(@) > `0`): true
                    Name:
                      (length(@) > `0`): true
