apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-instance-environment-tag
  annotations:
    policies.kyverno.io/category: OCI Best Practices
    policies.kyverno.io/severity: Critical
spec:
  rules:
    - name: check-instance-environment-tag
      match:
        all:
          # - ($analyzer.resource.type): terraform-plan
          - (planned_values.root_module.child_modules[].resources[?type=='oci_core_instance'][] | length(@) > `0`): true
      assert:
        any:
          - message: Check that the Environment tag for instances conforms to TIAA standard Instance naming convention.
            check:
              ~.(planned_values.root_module.child_modules[].resources[?type=='oci_core_instance'][]):
                values:
                  freeform_tags:
                    Environment:
                      (contains(@, 'DV') || contains(@, 'ST') || contains(@, 'DR') || contains(@, 'PD') ): true
